### ISSUE TITLE
User preferences

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/gramps-webapi#143]
@DavidMStraub @Nick-Hall I have been thinking about user preferences a little so wanted to open a discussion about them.  

Given that we have the separate database for user authentication, does it make sense to store their preferences in it as well and should we provide for that in the api?

I am thinking if we do eventually support multiple trees it should account for that as some preferences might be global in nature and others tree specific.  And if someday more than one application is written to use the API I am wondering if it should allow for that to store preferences in a separate namespace as well or if that is overkill.

Some kind of key / value store probably makes the most sense.  The value would be a string and so could store anything, even stringified json. So if you stored report preferences all the preferences for a specific report could be grouped together instead of each needing a separate key. 

To that end I am wondering if something like this makes sense:

`/api/users/-/preferences/{application_id}/{tree_name}/{key}`

This follows the convention used for the password reset endpoint with the `-` for current user. 

To differentiate global from tree specific attributes we could use `-` as the tree name for those as well.  

This kind of scheme would let an application user set, say, a prefered pagesize of 15 globally and then at the tree level set the home person for that tree. Well, if the application supported it of course.

I suppose things like Gramps ID prefixes still need to be in Gramps. I think I saw methods for those in the database class, I should look at that again. Researcher too probably needs to stay there.  Those are tree specific preferences and not tied to a specific user. 

We expose bookmarks and filters in the API and those are both problematic.  The bookmarks are global at the database level.  So if you added bookmark support to [Gramps.js](https://github.com/DavidMStraub/Gramps.js) everyone would share the same set of bookmarks which is not desirable. The custom filters construct is global across all the trees in Gramps as it is stored in a self contained XML file which is also not desirable. 

So if we added this type of support in the API it would make sense to refactor those things to work off of the user preferences and not use the Gramps native constructs at all anymore.

And then I guess another question is should there be some kind of backup/restore or export/import for the user authentication database as well.

Any thoughts about these things?

**Comment by DavidMStraub** [comment]
Hi,

I also have some ideas about this (which are a bit different but happy to discuss). After Christmas I'll write in more detail. I agree in general that it would be great to have multi-database support.

**Comment by DavidMStraub** [comment]
Some comments:

> Given that we have the separate database for user authentication, does it make sense to store their preferences in it as well and should we provide for that in the api?

So far, my thinking was that the user database should contain as little information as possible - namely, only what is needed to authenticate & to authorize. That way, it could also be fairly easily swapped by a different authentication method for certain deployments - e.g. some kind of single sign-on.

I would prefer if we didn't have *any* user configuration in the API. We also don't have any sessions - the user DB is only queried to fetch a token. Not even to check permissions it's necessary to query the API, since these are encoded in the token. Having configuration would either require encoding all of it in the token or going to a scheme where apps would have to query the user DB all the time.

Instead, I would prefer to specify configuration options entirely as query parameters on the API, such as the `locale` we already have. Eventually I think we should offer several things that are currently handled via the Gramps config file as query parameters, e.g. place formats. This would also allow different apps using different config - e.g. in Gramps.js I prefer having very short place names (i.e. just the place name), while different apps might prefer having long place names (including the hierarchy).

This means the configuration would be entirely in the responsibility of the application. This also makes sense sine the configuration will be very *dependent* on the application. 

> I am thinking if we do eventually support multiple trees it should account for that as some preferences might be global in nature and others tree specific. And if someday more than one application is written to use the API I am wondering if it should allow for that to store preferences in a separate namespace as well or if that is overkill.

Fully agree that we should think about different trees. But given the way the authentication works, I would suggest to strictly bind a single "user" to a single tree. This would not preclude a "hub application" where a single "hub user" could have access to several trees; but switching trees in the "hub application" would then correspond from the API point of view to fetching a new token with a new "user".

> We expose bookmarks and filters in the API and those are both problematic. The bookmarks are global at the database level. So if you added bookmark support to Gramps.js everyone would share the same set of bookmarks which is not desirable. The custom filters construct is global across all the trees in Gramps as it is stored in a self contained XML file which is also not desirable.
> So if we added this type of support in the API it would make sense to refactor those things to work off of the user preferences and not use the Gramps native constructs at all anymore.

Fully agree. Some sort of "shared" global bookmarks and filters could still make sense - e.g. the tree owner could have some filters that select a certain family branch which is useful to multiple users - but in general I think filters and bookmarks should be handled by the apps. Since we already support the necessary query arguments, it's easy for any app to just store that any way the want, so I don't see a necessity for us to handle that in the backend. 

> And then I guess another question is should there be some kind of backup/restore or export/import for the user authentication database as well.

In my opinion that's a server management issue and not relevant to the API. For instance, I use docker volumes for all the data that needs to persist.

**Comment by cdhorn** [comment]
Yes I see your point of view, let the application maintain state elsewhere. 

That is cleaner in the long run than trying to provide services to save application state as well and keeps the API more focused.  You have made a convincing argument, I agree. 

We have added a bit of logic in the API now that really belongs in the Gramps core package.  The search engine, timelines, additional sort keys, and the date filter come to mind. They are worthwhile enhancements though and Gramps seems to iterate at a slower pace.

**Comment by DavidMStraub** [comment]
> We have added a bit of logic in the API now that really belongs in the Gramps core package. The search engine, timelines, additional sort keys, and the date filter come to mind. They are worthwhile enhancements though and Gramps seems to iterate at a slower pace.

Yes, I agree. We can open pull requests for those features and once they are merged and a new Gramps version released remove it from this package.

**Comment by cdhorn** [comment]
Closing based on architectural decision/understanding.
