### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#158]
I suggest to have a release 0.1 as soon as all issues labelled "bug" are closed.

**Comment by cdhorn** [comment]
I agree.

**Comment by DavidMStraub** [comment]
I was a bit distracted, but I think we can make a release. What do you think would be an appropriate version number? 0.1, 1.0?

We should then also make an announcement in the forums and perhaps the mailing lists.

**Comment by cdhorn** [comment]
I've been distracted too with a number of things and may be a while yet.

I agree we should release and announce something.

Not sure on version, should 1.0 have full write support or should that be 2.0? Nick was talking about adding JSON patch support in the base Gramps code possibly, do we wait for that first before adding write support?

If full write support is the goal for 1.0 then I'd say maybe version .5 or something to that effect since we haven't done anything with that yet.  If not then maybe .9 and see if anyone else makes use of it and has any feedback before promoting it to 1.0

Assuming enhanced places, UUID and additional URL support are in 5.2 and that was slated for April should 1.0 wait and go out with that at the same time since that affects the schema and thus API?  If so then .9 now and 1.0 then would seem to make the most sense, with 2.0 being for write support later on.

As project lead for the API I see it as your and Nick's call.  😀

**Comment by DavidMStraub** [comment]
Good points, in any case it makes sense to wait at least until the 5.2 release before tagging 1.0, since users will expect the API to be mostly stable after that.

In that case I would just go for 0.1 and release frequently (so we will arrive at 0.5 and 0.9 as well :wink:).

**Comment by DavidMStraub** [comment]
Finally ready. I would do the release tomorrow.

**Comment by DavidMStraub** [comment]
`v0.1` released on Github

I had to make a change to `setup.py` after that before the PyPI upload because I realized the package name did not agree with what we decided in #129 (module `gramps_webapi`, PyPI package `gramps-webapi`).

The PyPI package is here: https://pypi.org/project/gramps-webapi/

I also made an announced post in the forum: https://gramps.discourse.group/t/gramps-web-api-first-release/1609

**Comment by Nick-Hall** [comment]
@DavidMStraub Would you also like me to announce this on the _gramps-announce_ mailing list and perhaps as a blog post?

**Comment by DavidMStraub** [comment]
Yes, good ideas!
