### ISSUE TITLE
Migrate unit tests to Github actions

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#180]
https://app.travis-ci.com/github/gramps-project/gramps-webapi/jobs/521477366

> Job has been terminated due to insufficient credits balance

@Nick-Hall, any idea what's wrong? I thought there are no limits for open source projects.

**Comment by Nick-Hall** [comment]
Since the migration from `travis-ci.org` to `travis-ci.com`, we now have a limited number of free credits.  They didn't make it clear how long they should last.  I can ask for some more.

Perhaps we should move to GitHub Actions though.  I started to investigate this for our main repository with PR [#1241](https://github.com/gramps-project/gramps/pull/1241).

**Comment by DavidMStraub** [comment]
Yes, that might be more stable and for this project it should be simple to make the switch.
