### ISSUE TITLE
Undo transaction

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#320]
It would be nice to be able to post a transaction to the `transactions` endpoint with an option `invert` that exchanges `add` with `delete` and exchange new with old objects for `modify`, such that one could post the transactions returned from PUT or POST endpoints to implement an undo option.

**Comment by Nick-Hall** [comment]
When we get around to changing the internal raw format of objects to JSON, I'd also like to store [JSON patches](https://jsonpatch.com) in the transaction log.  Then an undo would simply involve applying patches.

**Comment by DavidMStraub** [comment]
> When we get around to changing the internal raw format of objects to JSON, I'd also like to store [JSON patches](https://jsonpatch.com) in the transaction log. Then an undo would simply involve applying patches.

Interesting idea. Can you elaborate on which transaction log that would be?

For web API specifically, I was also thinking about storing transactions in a separate database table; we already have a  `transaction_to_json` function (https://github.com/gramps-project/gramps-webapi/blob/master/gramps_webapi/api/resources/util.py#L1058). This would allow storing the user who made the change along with it and make it possible to have a kind of change long.

**Comment by Nick-Hall** [comment]
I was talking about the undo functionality.  We store [DbTxn](https://github.com/gramps-project/gramps/blob/master/gramps/gen/db/txn.py#L53) objects in a list in [DbGenericUndo](https://github.com/gramps-project/gramps/blob/master/gramps/gen/db/generic.py#L71).

The problem is that we store snapshots of objects in the transaction, which will obviously cause problems in a multi-user environment.  If we moved to storing patches instead, this would open the way for multi-user access to a single database.

**Comment by DavidMStraub** [comment]
Right, I'm just wondering where to store it. A web app opens & closes the database connection with every request, so there is no Python object to store it in like for the desktop app. The simplest solution would be a database table.

**Comment by DavidMStraub** [comment]
I realized I never answered this question, I think the answer is yes - actually I think it can be achieved by fairly light changes to `DbGenericUndo`. I'll give it try when I have time.
