### ISSUE TITLE
Mixed up notes (my notes and error messages after GEDCOM import)

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-webapi#439]
After GEDCOM import I found several thousands of error messages as notes. They are mixed up with my own notes. I would prefer to see the error messages in a log file.

**Comment by DavidMStraub** [comment]
I understand, and without saying that this is good or should be like this, I think we can't do anything about it in Gramps Web because the Gedcom import is handled entirely by Gramps (core). I suggest to open a bug report against Gramps, or to write feedback in the [Gramps Discours forum](https://gramps.discourse.group/). There is also a comprehensive discussion of import subtleties in the Wiki, https://www.gramps-project.org/wiki/index.php/Import_from_another_genealogy_program.
